baseURL = 'https://entropyhackers.org/'
 
languageCode = "en-us"
# title = "Entropy Hackers"
    theme = "hello-friend-ng"
    relativeURLs = true
    canonifyURLs = false
  
enableSharingButtons = true

copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'


 [params.logo]
    logoMark     = "$"
    logoText     = "cd /entropy/hackers"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
    # logoCursorPathname = true

[params]
    # siteTitle  = "Entropy Hackers"
    # homeSubtitle = "reversing time and space"

    dateFormat = "02.01.2006"
    defaultTheme = "icy-dark"
    footerText = "Just a text"
    showPoweredBy = true
    showBuiltWith = true
    customCSS = ["/css/custom.css"]   

[params.author]
    name = "Secretary of Chaos"
    url = "https://entropyhackers/contact/"

[params.footer]
    trademark = 2025
    rss = true
    copyright = true
    author = true
    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

[[params.social]]
    name = "email"
    url  = "mailto:office@entropyhackers.org"

[[params.social]]
    name = "github"
    url  = "https://github.com/Entropy-Hackers"


[[menu.main]]
  identifier = "about"
  name = "About us"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "contact"
  name = "Get in touch"
  url = "/contact/"
  weight = 3